spring.application.name=DemoSpringBoot
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=vidu1;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2;characterEncoding=UTF-8

spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto = update

server.port=8092

# ========= THYMELEAF (thay cho JSP) =========
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ========= ENCODING / I18N =========
spring.mvc.locale=vi_VN
spring.mvc.locale-resolver=fixed
spring.web.locale=vi_VN
spring.messages.encoding=UTF-8